# Generated by Django 2.2.5 on 2021-07-13 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='school',
            old_name='location',
            new_name='ans',
        ),
        migrations.RenameField(
            model_name='school',
            old_name='name',
            new_name='ques',
        ),
        migrations.RemoveField(
            model_name='school',
            name='principal',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
