# Generated by Django 2.2.5 on 2021-07-18 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0003_auto_20210714_0735'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolSt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ques', models.TextField()),
                ('ans', models.TextField(blank=True)),
            ],
        ),
        migrations.AlterField(
            model_name='school',
            name='ans',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='ques',
            field=models.TextField(),
        ),
    ]
